# General setting
is:
  keycloak:
    admin:
      user: powerbiz_web_app_testing
      password: yf"YRcF7dJ='Y<3GuGbAtQ7.qqweqwrqwfsdfsdf
server:
  port: 8888

# Keycloak settings
keycloak:
  #  realm: SpringBootKeycloak
  realm: PowerBiz
  #  auth-server-url: http://localhost:8080/auth
  auth-server-url: https://dev.auth.portal.powerbiz.asia/auth
  #  ssl-required: none
  ssl-required: all
  resource: powerbiz-dev

  #  resource: springboot-keycloak
  #  resource: app1
  #  resource: powerbiz-dev
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username
  public-client: true
#  client-id: login-app
#  client-secret: RD6vw5aRNDr2S8AJoZ50HNoz3LuMCKKw
#  scope: openid, profile
#  authorization-grant-type: password
client-resource2: login-app


#spring:
#  main:
#    allow-circular-references: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=True
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

