# General setting
is:
  keycloak:
    admin:
      user: initial1
      password: 1234
server:
  port: 8888

# Keycloak settings
keycloak:
  realm: SpringBootKeycloak
  auth-server-url: http://localhost:8180/auth
  ssl-required: none
  resource: login-app
  use-resource-role-mappings: true
  bearer-only: true
  cors: true
  principal-attribute: preferred_username
  public-client: true
#spring:
#  main:
#    allow-circular-references: true
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/account?createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Jakarta&useSSL=false&allowPublicKeyRetrieval=True
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
    show-sql: true

